# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-23 02:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='fileupload/', verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('uptime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u4e0a\u4f20',
                'verbose_name_plural': '\u6587\u4ef6\u4e0a\u4f20',
            },
        ),
        migrations.CreateModel(
            name='QQContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='\u884c\u53f7')),
                ('qqname', models.CharField(max_length=50, verbose_name='QQ\u540d\u79f0')),
                ('content', models.CharField(max_length=500, verbose_name='\u804a\u5929\u5185\u5bb9')),
                ('qqdate', models.DateTimeField(verbose_name='\u804a\u5929\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'QQ\u804a\u5929\u8bb0\u5f55',
                'verbose_name_plural': 'QQ\u804a\u5929\u8bb0\u5f55',
            },
        ),
    ]
