# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-23 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qqhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqcontent',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='\u804a\u5929\u5185\u5bb9'),
        ),
    ]
