# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-04 02:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qqhome', '0002_auto_20180523_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileup',
            name='parseris',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=2, verbose_name='\u662f\u5426\u5206\u6790'),
            preserve_default=False,
        ),
    ]
